### ISSUE TITLE
Transaction database is not immutable

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#10]
Idea is to use a Postgres or MySQL user that only has insert permission for a transaction table.

**Comment by wildarch** [comment]
I want to propose the following changes to the credit management system to accomodate this and #37:

The `Transaction` model will be changed to the following SQL table:
```sql
CREATE TABLE transactions (
  id UUID NOT NULL PRIMARY KEY,
  date TIMESTAMP WITH TIMEZONE NOT NULL,
  source_user FOREIGN KEY REFERENCES Users(id) NULL,
  source_association FOREIGN KEY REFERENCES Associations(id) NULL,
  target_user FOREIGN KEY REFERENCES Users(id) NULL,
  target_association FOREIGN KEY REFERENCES Associations(id) NULL,
  amount MONEY NOT NULL,
  notes TEXT NULL,
  CHECK(amount > 0),
  CHECK(source_user IS NULL OR source_association IS NULL), -- there must be at most one source
  CHECK(target_user IS NULL OR target_association IS NULL), -- there must be at most one target
  CHECK(source_association IS NULL OR target_association IS NULL), -- associations may not send each other money.
);
The `AssociationCredits` and `UserCredit` tables are removed, and are replaced by the following views (not tables):
```sql
CREATE VIEW association_balance_mutations AS
SELECT target_association as id, amount
FROM transactions
WHERE  target_association IS NOT NULL
UNION
SELECT source_association as id, -SUM(amount)
FROM transactions
WHERE source_association IS NOT NULL;

CREATE VIEW association_balance AS
SELECT id, SUM(amount)
FROM association_balance_mutations
GROUP BY id;

CREATE VIEW user_balance_mutations AS
SELECT target_user as id, amount as mutation
FROM transactions
WHERE  target_user IS NOT NULL
UNION
SELECT source_user as id, -amount as mutation
FROM transactions
WHERE source_user IS NOT NULL;

CREATE VIEW user_balance AS
SELECT id, SUM(amount)
FROM user_balance_mutations
GROUP BY id;
```

We should then make a user `dining-server` in Postgres that has only `SELECT` and `INSERT` right on the `transactions` table.

There is one constraint we unfortunately cannot have postgres check for us: The requirement that associations have no negative balance, and the bottom limit for the user balance. However, since that is not a constraint that threatens the integrity of the table itself, I think we can afford to perform those checks in django.

**Comment by DutcherNL** [comment]
It's not reasonable to say associations can not have a negative balance. Especially since associations can be traaced easily and can just be send a bill every month/ quartile whatever. Having an association be unable to wire money to their members because Scala is acting slow works against the final users as should therefore be unwanted.

**Comment by mhvis** [comment]
> There is one constraint we unfortunately cannot have postgres check for us: The requirement that associations have no negative balance, and the bottom limit for the user balance. However, since that is not a constraint that threatens the integrity of the table itself, I think we can afford to perform those checks in django.

Agreed :smile: 

> `CHECK(source_association IS NULL OR target_association IS NULL), -- associations may not send each other money.`

I would say that this a business rule, just like the bottom limit for the user balance, and as business rules might change over time it's maybe nicer to implement those in Django, and have the database constraints just for ensuring the integrity of the data.

I assume the `notes` column is for storing a description of the transaction, like 'deposit via Q treasurer'? If so, okay :+1: and if not, we might want to add that.

I'm fine with the proposal for the remaining part :smile: . When we notice slow queries during profiling we could try adding indexes to the source and target columns since we'll need to select on those a lot. For the balance I'd say that it could possibly be implemented as a direct query instead of a view, as the view is just an abstraction of the query and I think that the abstraction is not needed.

These mentioned changes are suggestions, I'm also fine with leaving it how it is now.

**Comment by wildarch** [comment]
I think it makes sense to make the CHECK constraint a business rule. The `notes` column exists for exactly that purpose :smile:

**Comment by wildarch** [comment]
I don't have the time to implement this right now, but if someone wants to take a shot at it, I'd be happy to review the pull request :wink:
