### ISSUE TITLE
Association overview for Boardmembers

### ISSUE THREAD

**Issue by wildarch** [DutcherNL/Scala-Dining-WebApp#11]
Board members must be able to see an overview with information of all users from their associations.
This should be a table with the following columns:
- Username 
- Full name of user 
- email 
- balance 
- verified
This table can be sorted on all these elements

**Comment by DutcherNL** [comment]
Board members can now validate or unvalidate accounts and as a result clean the list. Current balance overviews not yet implemented.

**Comment by DutcherNL** [comment]
Table can not yet be ordered, I'll make a seperate issue for that as tables is a recurring element
