### ISSUE TITLE
UI missing for navigating to days outside current week

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#110]
It's not possible via the interface to go to days which are more than a week in advance or to go to past days.

**Comment by DutcherNL** [comment]
Conscious design choice to prevent creation of slots on the wrong date. Can be circumvented through url, but this is considered a conscious action

**Comment by mhvis** [comment]
Should be possible in the UI without changing the URL, as all legal actions should be possible using the UI. Solution would be to come up with a UI that clearly shows it when you're outside the current week range, but I haven't though about how to show that yet.
