### ISSUE TITLE
Dininglist purchasers can not add extra people

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#112]
Being co-owner it is counterintuitive to some they can't add people after sign-up limits (time/#)

**Comment by mhvis** [comment]
Possible suggestion: remove the distinction between purchaser and claimant, instead have a list of owners/managers for each dining list which have full permissions.

**Comment by mhvis** [comment]
Isn't this fixed?

**Comment by DutcherNL** [comment]
I believe so yeah, don't know why this was still open haha
