### ISSUE TITLE
Dining list creator should not automatically join the list

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#118]
Requested by Q board member, I personally agree

**Comment by DutcherNL** [comment]
I disagree, it's counterintuitive. In most cases (except for Quadrivium) people claiming a dining list will also join dinner as claiming it means they are responsible for ensuring a meal and noting down who did what (shopping, cooking, cleaning). It's fine if Q wants  to claim dining lists by someone who will not be present, but then they can sign out. Q, no offense, is the exception and we should not standardize exceptions

**Comment by mhvis** [comment]
Thinking of creating an option for it in user settings

**Comment by DutcherNL** [comment]
As long as that option is automatically enabled, yes.
