### ISSUE TITLE
Transactions: no amounts above 99.99 are supported

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#152]
This provides issues when trying to transfer money to associations to cancel their negative amount. Suggestion: max_digits=5 instead of 4.

Reason for not implemented yet: possible conflicts in fixed transaction table as that is locked on the server for changes if I'm not mistaken.

**Comment by mhvis** [comment]
yes, running the migration should result in a database error (hopefully). When the migration file is committed I can let it go through. I'd suggest to directly change it to a max amount that will never pose a problem, e.g. max_digits=6

**Comment by DutcherNL** [comment]
This is included in PR #153
