### ISSUE TITLE
No error when trying to subscribe to two dinner lists

### ISSUE THREAD

**Issue by wildarch** [DutcherNL/Scala-Dining-WebApp#20]
Users do not receive an error message when they attempt to subscribe to two different lists on one day. Their request is already refused, but users should also receive an error about this.

**Comment by DutcherNL** [comment]
Subscribe or create? I thought I already implemented double day subscriptions with a notification (you get a special page informing you of your current and intended dining list and a choice.
![afbeelding](https://user-images.githubusercontent.com/23361463/48921609-256f5a00-eea1-11e8-837b-3d0d44229b0a.png)
