### ISSUE TITLE
Longer comments, 256 characters is limited

### ISSUE THREAD

**Issue by Ndoll1** [DutcherNL/Scala-Dining-WebApp#244]
256 characters is too limited  when you want to share allergenlist from products. Or to share 2 normal length links

Possible solution:

Auto shorten links
Like twitter character counter

**Comment by mhvis** [comment]
I agree. The PR increases the comment length and adds linebreaks.

**Comment by mhvis** [comment]
#245 also sets the new limit of 10000 on the form field so that its not possible to enter a longer text. When @DutcherNL merged the PR it will be live.
