### ISSUE TITLE
CSS is custom made

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#26]
So that others can understand and work with the CSS it is maybe useful to switch over to a CSS framework such as Bootstrap. This has the advantage of having a very extensive documentation. Own adjustments can be added but should be minimal to keep the lines of code manageable.

**Comment by DutcherNL** [comment]
This has been severely reduced except a couple of small set-ups which can not be accomplished in Bootstrap.
