### ISSUE TITLE
Stylesheet does not use custom colour palette

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#45]
Some deviation from the colour palette is advised. The deep dark navy blue Scala uses for instance is a good header colour.

**Comment by mhvis** [comment]
Is this still relevant with the Bootswatch theme? It's possible to modify the bootstrap colors using SASS

**Comment by DutcherNL** [comment]
Then the problem is that it still does not have a custom palette, though is solvable with SASS.

**Comment by mhvis** [comment]
Okay well I'll leave it to you :smiley:
