### ISSUE TITLE
Dining page button layout

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#78]
For instance on a dining page is the following:

```html
<a class="btn btn-primary col-12 col-md-6 mt-3 " href="/4/3/2019/esmgq/change/">
    <i class="fas fa-tools"></i> Change information
</a>
<a href="/4/3/2019/esmgq/remove/" class="btn btn-outline-danger col-12 col-md-6 mt-3">
    <i class="fas fa-trash-alt"></i> Remove dining list
</a>
```

This leads to no gutter between the columns and should be:

```html
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary btn-block mt-3 " href="/4/3/2019/esmgq/change/">
            <i class="fas fa-tools"></i> Change information
        </a>
    </div>
    <div class="col-md-6">
        <a href="/4/3/2019/esmgq/remove/" class="btn btn-outline-danger btn-block mt-3">
            <i class="fas fa-trash-alt"></i> Remove dining list
        </a>
    </div>
</div>

**Comment by DutcherNL** [comment]
This was done deliberately, By making a row each time the effective width of the screen is reduced for each row which becomes a bit of a mark-up issue when going to phone-width. To keep the width as wide as possible no extensive use of rows was made.

**Comment by mhvis** [comment]
This should not be the case, the row and col classes compensate each other so that the width does not decrease when nesting. For that to work though you should always have separate divs for row, col and container, and row divs should always have col divs inside of them. Also you should use divs for these and not an a tag as in this case.

In the case above, the row div is missing and the col is not using a separate div.
