### ISSUE TITLE
Some pages miss login checks

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#87]

**Comment by mhvis** [comment]
* Create dining slot page
* All pages from the General app

**Comment by DutcherNL** [comment]
The navbar has been rewritten to allow non-logged in users to use the navbar in some cases. As a result, we can show a portion of the site for non-logged in users if we want to (for example for the rules and guidelines page). It does not abolish the need to block non-logged in users on most pages, it just allows some specific pages to always be shown if needed.

**Comment by mhvis** [comment]
Okay yes I see the commit
