### ISSUE TITLE
Association Details Non-nullable details are saved empty

### ISSUE THREAD

**Issue by DutcherNL** [DutcherNL/Scala-Dining-WebApp#9]
An additional guarantee on model creation is requested

**Comment by mhvis** [comment]
Can you explain this issue further? I don't fully understand it.

**Comment by DutcherNL** [comment]
Upon creation of an Association the Association Details is saved automatically with empty strings. The not-nullable characteristic of the model however is ignored in this process. This could result in url problems as the shorthand too contains no data.

**Comment by DutcherNL** [comment]
Fixed in recent Association implementation
