### ISSUE TITLE
Transaction creator not stored

### ISSUE THREAD

**Issue by mhvis** [DutcherNL/Scala-Dining-WebApp#98]
The source user account for a transaction is not stored as far as I can see

**Comment by DutcherNL** [comment]
You mean for associations? For users it can be nothing else than the user (unless the transaction is made in the admin panel, but that's hard to prevent)

**Comment by mhvis** [comment]
Yes, when the source of a transaction is an association it would be important to also store the user from that association that created this transaction for auditing purposes so that it's possible to trace back the user that created it.
